# Generated by Django 6.0.2 on 2026-02-11 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('compra', 'Compra'), ('bonus_proveedor', 'Bonus Proveedor'), ('ajuste_manual', 'Ajuste Manual')], max_length=20)),
                ('puntos', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clinica')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Puntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_acumulados', models.IntegerField(default=0)),
                ('numeros_sorteo', models.IntegerField(default=0)),
                ('posicion_ranking', models.IntegerField(blank=True, null=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.clinica')),
            ],
        ),
    ]
