# Generated by Django 6.0.2 on 2026-05-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text="Describe qué incluye el premio (ej. 'Kit de limpieza premium' o '5% dto. en próxima compra').")),
                ('coste_puntos', models.PositiveIntegerField(help_text='Número de DQ Coins necesarios para canjear este premio.')),
                ('imagen_url', models.URLField(blank=True, help_text='URL de imagen representativa del premio.')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el catálogo.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Premio',
                'verbose_name_plural': 'Premios',
                'ordering': ['orden', 'coste_puntos'],
            },
        ),
    ]
