# Generated by Django 6.0.2 on 2026-05-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentivos', '0002_add_premio_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='premio',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen subida al servidor.', null=True, upload_to='premios/'),
        ),
    ]
