# Generated by Django 6.0.2 on 2026-02-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompraHistorica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('trimestre', models.IntegerField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
