# Generated by Django 6.0.2 on 2026-02-11 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0002_initial'),
        ('compras', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprahistorica',
            name='clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clinica'),
        ),
        migrations.AddField(
            model_name='comprahistorica',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.proveedor'),
        ),
    ]
