# Generated by Django 6.0.2 on 2026-02-11 11:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CompraAgrupada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio_objetivo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_minima', models.IntegerField()),
                ('cantidad_actual', models.IntegerField(default=0)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_linea', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio_oferta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('destacada', models.BooleanField(default=False)),
                ('enviar_notificacion', models.BooleanField(default=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_pedido', models.CharField(max_length=50, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('tipo_gestion', models.CharField(choices=[('checkout_propio', 'Checkout Propio'), ('redireccion_proveedor', 'Redireccion Proveedor')], max_length=30)),
                ('url_seguimiento', models.URLField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notas', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('codigo_producto', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('precio_mercado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_dq', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_disponible', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='proveedores/')),
                ('es_estrategico', models.BooleanField(default=False)),
                ('condiciones_especiales', models.TextField(blank=True)),
                ('contacto_nombre', models.CharField(max_length=100)),
                ('contacto_email', models.EmailField(max_length=254)),
                ('contacto_telefono', models.CharField(max_length=20)),
                ('url_web', models.URLField(blank=True)),
                ('url_catalogo', models.URLField(blank=True)),
                ('pdf_tarifas', models.FileField(blank=True, null=True, upload_to='tarifas/')),
                ('modo_pedido', models.CharField(choices=[('email_pedido', 'Email Pedido'), ('redireccion_web', 'Redireccion Web'), ('api_rest', 'API REST'), ('edi', 'EDI')], default='email_pedido', max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
