# Generated by Django 6.0.2 on 2026-02-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='descripcion_larga',
            field=models.TextField(blank=True),
        ),
    ]
