# Generated by Django 6.0.2 on 2026-03-12 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_proveedor_descripcion_larga'),
        ('core', '0003_clinica_num_boxes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='bloque',
            field=models.CharField(choices=[('A', 'Direct Sale'), ('B', 'Lead/Quote')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='categoria',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='compras.categoria'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='codigo_descuento',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo_interaccion',
            field=models.CharField(choices=[('link', 'Link'), ('lead_form', 'Lead Form')], default='link', max_length=20),
        ),
        migrations.CreateModel(
            name='LeadSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_interes', models.TextField()),
                ('estado', models.CharField(choices=[('Pending', 'Pending'), ('Contacted', 'Contacted'), ('Closed', 'Closed')], default='Pending', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clinica')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.proveedor')),
                ('usuario_solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoEstrella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_mercado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_dq', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos_estrella/')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.proveedor')),
            ],
        ),
    ]
