# Generated by Django 6.0.2 on 2026-04-13 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_categoria_bloque_categoria_parent_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='categoria',
                    name='bloque',
                ),
            ],
            database_operations=[]
        )
    ]
