# Generated by Django 6.0.2 on 2026-04-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_remove_categoria_bloque'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='descuento_dq',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='descuento_mercado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
