# Generated by Django 6.0.2 on 2026-04-15 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_proveedor_descuento_dq_proveedor_descuento_mercado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto (Marketplace)', 'verbose_name_plural': 'Productos (Marketplace)'},
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='URL of a generic reference image'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('nombre', 'marca')},
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos_marketplace', to='compras.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(db_index=True, max_length=300),
        ),
        migrations.CreateModel(
            name='ProductoLegado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('codigo_producto', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('precio_mercado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_dq', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_disponible', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.categoria')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.proveedor')),
            ],
            options={
                'verbose_name': 'Producto (Legado)',
                'verbose_name_plural': 'Productos (Legado)',
            },
        ),
        migrations.AlterField(
            model_name='compraagrupada',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.productolegado'),
        ),
        migrations.AlterField(
            model_name='lineapedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.productolegado'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.productolegado'),
        ),
        migrations.RemoveField(
            model_name='producto',
            name='codigo_producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_dq',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_mercado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_disponible',
        ),
        migrations.CreateModel(
            name='ProveedorOferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Unique product ID from the supplier website', max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('url_compra', models.URLField(blank=True, help_text='Direct link to the product page on the supplier website')),
                ('stock_status', models.CharField(choices=[('in_stock', 'En stock'), ('low_stock', 'Stock bajo'), ('out_of_stock', 'Sin stock'), ('unknown', 'Desconocido')], default='unknown', max_length=20)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='compras.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_marketplace', to='compras.proveedor')),
            ],
            options={
                'verbose_name': 'Oferta de Proveedor',
                'verbose_name_plural': 'Ofertas de Proveedor',
                'ordering': ['precio'],
                'unique_together': {('proveedor', 'sku')},
            },
        ),
    ]
