# Generated by Django 6.0.2 on 2026-04-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_marketplace_producto_proveedor_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='needs_review',
            field=models.BooleanField(default=False, help_text='Flag automatically set if semantic similarity with other products suggests a duplicate'),
        ),
    ]
