# Generated by Django 6.0.2 on 2026-04-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_producto_needs_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='linea_producto',
            field=models.CharField(blank=True, help_text='Conceptual product line for grouping and procurement highlights', max_length=300),
        ),
    ]
