# Generated by Django 6.0.2 on 2026-04-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_producto_linea_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='logo_url',
            field=models.URLField(blank=True, help_text='External logo URL (overrides uploaded logo file)'),
        ),
    ]
