# Generated by Django 6.0.2 on 2026-04-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0010_proveedor_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='ahorro_estimado',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Porcentaje de ahorro estimado (Diferencial). Ej: 0.05 para 5%.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='categoria_principal',
            field=models.CharField(blank=True, help_text='Clasificación macro del proveedor según el Excel financiero.', max_length=255, null=True),
        ),
    ]
