# Generated by Django 6.0.2 on 2026-05-07 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0011_proveedor_ahorro_estimado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.producto'),
        ),
    ]
