# Generated by Django 6.0.2 on 2026-05-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0012_alter_oferta_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
