# Generated by Django 6.0.2 on 2026-05-15 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0013_producto_imagen'),
        ('core', '0006_expensecategory_min_quarterly_consumption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeticionPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_valorado', models.CharField(max_length=255)),
                ('marca_referencia', models.CharField(blank=True, max_length=255)),
                ('plazo_entrega', models.CharField(choices=[('Urgente', 'Urgente'), ('Lo antes posible', 'Lo antes posible'), ('No es importante', 'No es importante')], max_length=50)),
                ('forma_pago', models.CharField(choices=[('Contado', 'Contado'), ('Financiación/Renting/Leasing', 'Financiación/Renting/Leasing'), ('Indiferente', 'Indiferente')], max_length=50)),
                ('precio_referencia', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Gestión', 'En Gestión'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=20)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clinica')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
