# Generated by Django 6.0.4 on 2026-05-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0014_peticionpresupuesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaDestacada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='ofertas_destacadas/')),
                ('url_destino', models.URLField(blank=True, help_text='URL to redirect when clicking the offer button')),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0, help_text='Lower number = shown first')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Oferta Destacada',
                'verbose_name_plural': 'Ofertas Destacadas',
                'ordering': ['orden', '-fecha_creacion'],
            },
        ),
    ]
