# Generated by Django 6.0.2 on 2026-02-14 11:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nombre_norm', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Expense Categories',
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('checksum', models.CharField(max_length=64, unique=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('stats', models.JSONField(default=dict)),
            ],
        ),
        migrations.RemoveField(
            model_name='clinica',
            name='cif',
        ),
        migrations.RemoveField(
            model_name='clinica',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='clinica',
            name='email',
        ),
        migrations.RemoveField(
            model_name='clinica',
            name='telefono',
        ),
        migrations.AddField(
            model_name='clinica',
            name='nombre_norm',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ClinicAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias_raw', models.CharField(max_length=200)),
                ('alias_norm', models.CharField(db_index=True, max_length=200, unique=True)),
                ('method', models.CharField(default='unresolved', max_length=50)),
                ('confidence', models.FloatField(default=0.0)),
                ('ignore', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aliases', to='core.clinica')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicLegalEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cif', models.CharField(max_length=20, unique=True)),
                ('reg_sanitario', models.CharField(blank=True, max_length=100)),
                ('nombre_fiscal', models.CharField(blank=True, max_length=200)),
                ('direccion', models.TextField(blank=True)),
                ('poblacion', models.CharField(blank=True, max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email_preferred', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_entities', to='core.clinica')),
            ],
            options={
                'verbose_name': 'Legal Entity',
                'verbose_name_plural': 'Legal Entities',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='legal_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cliniclegalentity'),
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('quarter', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source_sheet', models.CharField(max_length=100)),
                ('source_row', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.expensecategory')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='core.clinica')),
                ('last_import_batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.importbatch')),
            ],
            options={
                'indexes': [models.Index(fields=['clinic', 'year', 'quarter'], name='core_gasto_clinic__7d8a5f_idx')],
                'unique_together': {('clinic', 'year', 'quarter', 'category')},
            },
        ),
    ]
