# Generated by Django 6.0.2 on 2026-02-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_expensecategory_importbatch_remove_clinica_cif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='num_boxes',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
