# Generated by Django 6.0.2 on 2026-04-13 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_remove_categoria_bloque'),
        ('core', '0003_clinica_num_boxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='compras.proveedor'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='num_boxes',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
