# Generated by Django 6.0.2 on 2026-05-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0013_producto_imagen'),
        ('core', '0004_gasto_proveedor_alter_clinica_num_boxes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gasto',
            unique_together={('clinic', 'year', 'quarter', 'category', 'proveedor')},
        ),
        migrations.AddField(
            model_name='gasto',
            name='ahorro_aprox',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
