# Generated by Django 6.0.2 on 2026-05-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_gasto_unique_together_gasto_ahorro_aprox'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='min_quarterly_consumption',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
